mbl-core/tests/libs/mbed-crypto/test_mbed-crypto.py
For IOTMBL-2145: Create recipe for mbed-crypto
**Related PRs**
* meta-mbl PR: https://github.com/ARMmbed/meta-mbl/pull/576 (Should be merged before https://github.com/ARMmbed/mbl-config/pull/51).
* mbl-config PR: https://github.com/ARMmbed/mbl-config/pull/51 (Should be merged before this PR).
**Testing done**
*  Copied the the test script to target and manually run pytest.
=> Add pytest script to run mbed-crypto tests

ci/lava/tests/psa-arch-tests.py, ci/lava/tests/psa-arch-tests.yaml
For IOTMBL-2147: Create recipe for psa-arch-tests
**Related PRs**
* https://github.com/ARMmbed/meta-mbl/pull/598 (to add psa-arch-tests recipe).
* second meta-mbl PR coming soon (to update the mbl-core SRCREV after this PR is merged). 
* https://github.com/ARMmbed/mbl-tools/pull/246 (to add a Lava test plan to run the script from this PR). 
* https://github.com/ARMmbed/mbl-jenkins/pull/111 (to add the new test plan to the warrior-dev Jenkins build). 
**Jenkins and Lava links**
* See https://github.com/ARMmbed/meta-mbl/pull/598
=> Add script to run psa-arch-tests

ci/lava/tests/rootfs-update.sh, ci/lava/tests/rootfs-update.yaml
The refactor is needed because the script now doesn't assume the state
of the board. The rootfs to check is passed as argument by the parent
process (e.g.: LAVA pipeline which knows the state of the DUT)
Related ticket: IOTMBL-2258
=> Refactor rootfs-update scripts

cloud-services/mbl-cloud-client/scripts/CMakeLists.txt, cloud-services/mbl-cloud-client/scripts/arm_update_activate.sh, cloud-services/mbl-cloud-client/scripts/arm_update_active_details.sh, cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in
In MBL we're going to get rid of the bootflags partition and move our
boot flag files somewhere else. Unfortunately the firmware update
scripts assumed that the directory containing the bootflags was a mount
point and they hardcoded the path to this directory.
We previously had a mechanism to source a "local config script" in to
the update scripts, but this was a hack and I don't want to extend it.
Instead, use CMake's file configuration mechanism to allow distro
specific values to be injected into the scripts during a build.
**Jenkins links**
* See https://github.com/ARMmbed/meta-mbl/pull/638
**Related PRs**
* https://github.com/ARMmbed/meta-mbl/pull/638
=> Add mechanism to configure values in update scripts

cloud-services/mbl-cloud-client/scripts/CMakeLists.txt, cloud-services/mbl-cloud-client/scripts/arm_update_activate.sh, cloud-services/mbl-cloud-client/scripts/arm_update_active_details.sh, cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in
We have a 0.8 branch now so merge feature-partitioning into warrior-dev.
The branch contains a single commit on top of warrior-dev:
```
Add mechanism to configure values in update scripts
In MBL we're going to get rid of the bootflags partition and move our
boot flag files somewhere else. Unfortunately the firmware update
scripts assumed that the directory containing the bootflags was a mount
point and they hardcoded the path to this directory.
We previously had a mechanism to source a "local config script" in to
the update scripts, but this was a hack and I don't want to extend it.
Instead, use CMake's file configuration mechanism to allow distro
specific values to be injected into the scripts during a build.
```
**Related PRs**
https://github.com/ARMmbed/meta-mbl/pull/640
=> Merge feature-partitioning into warrior-dev

ci/lava/dependencies/enable-wifi.sh
The imx6ul should be treated the same as the imx7d and imx8 as it has the same qualcomm chipset.
=> Enable wifi on imx6ul

ci/lava/conftest.py, ci/lava/dependencies/create-python-environment-on-device.yaml, ci/lava/tests/build-tutorial-images.yaml, ci/lava/tests/core-component.yaml, ci/lava/tests/test-build-tutorial-images.py, ci/lava/tests/test-core-component.py, ci/lava/tests/test-systemd.py
Updated conftest.py to have a method of downloading files from URLs as
part of a fixture.
Updated conftest.py to control the debug output of execute_command using
the --debug_output option.
Updated core-component tests to allow the passing through of the
local.conf file.
Updated test-build-tutorial-images.py to have the steps as separate
tests instead of a single large function.
Tidied class names by removing underscores.
=> Pass local.conf to pytest.

ci/lava/tests/test-core-component.py
Change the shell command for the pytest running on the DUT to a proper login shell. This corrects path issues in the tests.
=> Fix the partitions test.

ci/lava/dependencies/wdog-test.service, ci/lava/dependencies/wdog-test.sh, ci/lava/tests/test-systemd.py
Add test cases for systemd watchdog management.
This commit also adds a mock systemd service file and shell script
to ci/lava/dependencies.
The service is used to check the watchdog is working. The service
is expected to terminate with SIGABRT if no keep-alive message is
sent from the service within 5 seconds of the service starting.
LAVA: 
https://lava.mbedcloudtesting.com/scheduler/job/66138
https://lava.mbedcloudtesting.com/scheduler/job/66139
https://lava.mbedcloudtesting.com/scheduler/job/66140
Do not merge until test jobs have completed and all tests passed.
=> ci:lava:tests: Add systemd watchdog test

cloud-services/mbl-cloud-client/scripts/arm_update_activate.sh
The busybox version of the tar command is apparently less sensitive about the order
of options passed in than GNU's version of tar. We need to support both
versions of tar, so change the order of the options passed to the tar
command.
Also clean up the decompressed update component file from /scratch
=> mbl-cloud-client:arm_update_activate: Change order of options passed to the tar

firmware-management/mbl-watchdog-init/CMakeLists.txt, firmware-management/mbl-watchdog-init/mbl-watchdog-init.c
For our robust update mechanism we need to initialise and set the
hardware watchdog timeout early in the boot process. This patch adds a
utility which can set the hardware watchdog timeout and query the system
for the last reboot reason.
Jenkins: http://jenkins.mbed-linux.arm.com/job/rw-test/162/
LAVA: http://e120856-lin.cambridge.arm.com/results.php?image_version=custom&image_number=162&custom_version=rw-test&lava_query=&lava_owner=&failures=false&submitter=robwal02&sort=by_job
=> firmware-management: Add mbl-watchdog-init utility

ci/lava/tests/bsp.yaml, ci/lava/tests/test-bsp.py
* Refactor BSP tests to work in lxc container.
Changed the BSP tests to run under pytest control. This removes the need
for the linaro repo.
=> Backport Refactor BSP tests to 0.9

mbl-core/tests/libs/psa-trusted-storage-linux/test_psa-trusted-storage-linux.py
This PR submits a test script for running the psa_trusted_storage_linux test binary.
=> Add test_psa-trusted-storage-linux.py for on-target running of test binaries

mbl-core/tests/libs/psa-trusted-storage-linux/test_psa-trusted-storage-linux.py
This commit corrects the test_psa-trusted-storage-linux.py to enable testing.
=> Fix test_psa-trusted-storage-linux.py to specify TESTS_PATH and TESTS correctly

ci/lava/conftest.py, ci/lava/helpers.py, ci/lava/tests/component-update.yaml, ci/lava/tests/test-component-update.py
Add a test to validate image updates using the test info file
generated by our create-update-payload script.
Also add a helpers.py module and move all test helper functions
there. Leave fixtures in conftest.py
NOTE: the rootfs test fails as we're either not rebuilding the rootfs properly in build-update-payloads or the "file_comparison_test" data from the testinfo is wrong, as the rootfs is updated (and the bank is switched) but the mtime of `/etc/build` doesn't change (which is the file the testinfo tells us to check).
=> ci:lava:tests: Add image update test.

ci/lava/conftest.py
Only skip update_method test types when update_method command line is set.
=> Fix pytest configuration to run parametized tests

ci/lava/dependencies/test-enable-wifi.py, ci/lava/tests/config-across-reboot.yaml, ci/lava/tests/test-config-across-reboot.py
Added new test to check that the config changes persist across a reboot.
This tests the hostname changes and the wifi setup.
Fixed error in test-enable-wifi.py which meant that WiFi wasn't always
enabled.
=> New test for checking configs persist.

ci/lava/tests/test-core-component.py, mbl-core/tests/partitions/test_partitions.py
sfdisk is no longer in the distro so this test was failing. 
Changed to extract the data from /sys/block files instead.
=> Update test to not use sfdisk

mbl-core/tests/partitions/test_partitions.py
Add test to check that the DEVICE_NAME files in
/config/factory/part-info match the actual device on which the
partitions live.
Why are we using re.escape() in get_var_for_part()? The values are being
put into a filename not a regex... Python is complaining about it too so
remove the re.escape()s in this function.
For IOTMBL-2656: Robust update: don't rely on root filesystem labels
=> test_partitions.py: add test for DEVICE_NAME files

ci/lava/tests/test-config-across-reboot.py
Added a sleep after the reboot to allow for WiFi to startup. 
The startup takes up to 60 seconds on some platforms.
Also changed the sleep after the ethernet is disabled to 60 seconds.
=> Added sleep for wifi to startup

cloud-services/mbl-cloud-client/scripts/apps_installer.sh, cloud-services/mbl-cloud-client/scripts/arm_update_activate.sh
If we're doing a multi-component update that includes both an app update
and an update of a component that requires a reboot to take effect,
don't let the app install script restart the cloud client part way
through the update.
We only actually need to restart the cloud client if we aren't going to
do a full reboot anyway, and if we restart the client part way through a
multi-component update (before the HEADER file has been moved) then the
cloud client will get confused.
For IOTMBL-2661: Multi-component update with app via pelion broken
=> update scripts: don't restart client halfway through update

ci/lava/dependencies/test-enable-wifi.py
The evaluation images need to have the Qualcomm driver installed in
order to enable WiFi. This was missed in the conversion to pytest.
=> Fix WiFi enable on imx devices.

ci/lava/dependencies/test-enable-wifi.py, ci/lava/helpers.py, ci/lava/tests/test-component-update.py, ci/lava/tests/test-config-across-reboot.py, cloud-services/mbl-cloud-client/scripts/apps_installer.sh, cloud-services/mbl-cloud-client/scripts/arm_update_activate.sh
* 62668ad - Fix WiFi enable on imx devices. (#260)
* e131f1c - update scripts: don't restart client halfway through update (#258)
* 838c065 - Added sleep for allow wifi to startup (#257)
* ab2485f - Fix component update test
* 706ba97 - Drop strings checks
* bca7b72 - Fix app test verification
=> mbl-os-0.10 -> warrior-dev backport

ci/lava/tests/test-cellular-and-wifi-host.py, ci/lava/tests/test-core-component.py
If the pytest running on the DUT fails the overall test does not register this as a failure. 
The return_code are checked against 0 to ensure something in the test execution fails.
=> Check return code from pytest on DUT

ci/lava/tests/test-component-update.py
We have an intermittent rootfs update failure on an RPI3b+ board in
the LAVA test farm. To help diagnose the cause of the failure dump the
output of some relevant logs in /var/log and the output of the
system journal after the update test.
=> test-component-update: Dump logfiles to console
